project:
  type: website
  preview:
    port: 5000
website:
  page-navigation: true
  reader-mode: true
  title: "Just a BLOG" 
  repo-url: "https://github.com/sysukili/kili_blog"
  repo-actions:  source
  description: "This is Kili's personal Blog."
  site-url: "https://sysukili.site"
  favicon: logo.svg
  open-graph:
    image: logo.png
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/)   @kili 2023-2025"
    right:
      - icon: github
        href: https://github.com/sysukili
      - icon: envelope
        href: sysukili@gmail.com

  navbar:
    logo: logo.svg
    search: true
    right:
      - text: About&CV
        href: about-zh.qmd
      - text: Posts/帖子
        href: posts/index.qmd
      - icon: github
        href: https://github.com/SYSUKili
      - text: bilibili
        href: https://space.bilibili.com/349744659
      - text: 推荐书籍
        href: books.qmd
      
      
format:                                # html 设置
  html:
    mainfont: LXGW Wenkai
        #["Inconsolata","LXGW Wenkai"]
    lang: zh
    smooth-scroll: true
    date-format: iso
    theme:
      light: [cosmo, styles.scss]
      dark: [darkly, theme-dark.scss]
    link-external-icon: true
    link-external-newwindow: true
#    link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true
    cap-location: margin
    

editor: visual

execute:                        # 执行设置
  freeze: auto
  warning: false
  error: false
  cache: true
  

